import "./globals.css";
import { Providers } from "../../components/providers";
import Navbar from "./UI/navbar";

export const metadata = {
  title: "E-Comm",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden"
      >
        <Navbar/>
        <Providers>
        {children}
        </Providers>
      </body>
    </html>
  );
}
